global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'h-pulse-mirage'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 5s

  - job_name: 'h-pulse-node'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/monitoring/node'
    scrape_interval: 10s 