version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"

  db:
    image: postgres:14
    container_name: h_pulse_postgres
    environment:
      POSTGRES_USER: h_pulse_user
      POSTGRES_PASSWORD: h_pulse_pass
      POSTGRES_DB: h_pulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
