# 前端构建镜像
FROM node:18 AS build

WORKDIR /app
COPY . /app

RUN npm install -g vite && npm install && npm run build

# 用 nginx 进行部署
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
